stages:
  - "build"
  - "deploy"

cache:
  key: "${CI_COMMIT_SHA}"
  paths:
    - "${CI_PROJECT_DIR}/output"

build:
  image: "python:3-slim"
  stage: "build"
  script:
    - "pip install virtualenv"
    - "virtualenv ."
    - "source ./bin/activate"
    - "pip install -r requirements.txt"
    - "pelican ${CI_PROJECT_DIR}/content -o ${CI_PROJECT_DIR}/output -s ${CI_PROJECT_DIR}/pelicanconf.py --relative-urls"

deploy:
  image: "alpine:latest"
  stage: "deploy"
  only: 
    - "master"
  script:
    - "apk add --update openssh sshpass"
    - "echo \"put -r output/* www\" | sshpass -p \"${sftp_password}\" sftp -oStrictHostKeyChecking=no ${sftp_login}@louis.mushland.xyz"
