name: Deploy website
on:
  push:
    # branches:
    #   - master
jobs:
  fetch:
    name: Fetch website source
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Download math result for job 1
      uses: actions/download-artifact@v1
      with:
        name: website
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to my server
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
